# Generated by Django 4.2.3 on 2023-08-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
