# Generated by Django 4.2.3 on 2023-08-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
