# Generated by Django 4.2.3 on 2023-08-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_userprofile_user_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=30, null=True, unique=True),
        ),
    ]
