# Generated by Django 4.2.3 on 2023-08-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_remove_user_avatar_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
