# Generated by Django 4.2.3 on 2023-08-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(height_field='height', null=True, upload_to='film/', width_field='width'),
        ),
    ]
