# Generated by Django 4.2.3 on 2023-07-31 16:45

import api.Films.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0002_film_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.CharField(max_length=50, verbose_name=api.Films.models.AllCountry),
        ),
    ]
