# Generated by Django 4.2.3 on 2023-07-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0003_allcountry_alter_film_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='country',
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.ManyToManyField(to='Films.allcountry'),
        ),
    ]
