# Generated by Django 4.2.3 on 2023-07-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0005_alter_film_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(height_field='height', upload_to='media/film/', width_field='width'),
        ),
    ]
