# Generated by Django 4.2.3 on 2023-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0006_alter_film_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(height_field='height', null=True, upload_to='media/film/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.IntegerField(choices=[], null=True),
        ),
    ]
